In [1]:
import pandas as pd
import json
import numpy as np

In [2]:
ds2_labels = pd.read_csv('/home/exp-1/Desktop/data/ds2_labels.csv')
ds2_labels.dropna()
ds3_labels = pd.read_csv('/home/exp-1/Desktop/data/ds3_labels.csv')
ds3_labels.dropna()

,Dst Port,Protocol,Timestamp,Label,date,id
0,22,6,22/02/2018 08:26:03,Benign,2018-02-22 08:26:03,2018-02-22 08:26:036
1,34989,6,22/02/2018 08:26:24,Benign,2018-02-22 08:26:24,2018-02-22 08:26:246
2,500,17,22/02/2018 08:25:10,Benign,2018-02-22 08:25:10,2018-02-22 08:25:1017
3,500,17,22/02/2018 08:25:10,Benign,2018-02-22 08:25:10,2018-02-22 08:25:1017
4,500,17,22/02/2018 08:24:59,Benign,2018-02-22 08:24:59,2018-02-22 08:24:5917
...,...,...,...,...,...,...
2097145,54116,6,23/02/2018 09:00:54,Benign,2018-02-23 09:00:54,2018-02-23 09:00:546
2097146,33914,6,23/02/2018 12:31:42,Benign,2018-02-23 12:31:42,2018-02-23 12:31:426
2097147,53,17,23/02/2018 12:15:24,Benign,2018-02-23 12:15:24,2018-02-23 12:15:2417
2097148,3389,6,23/02/2018 12:45:39,Benign,2018-02-23 12:45:39,2018-02-23 12:45:396
2097149,445,6,23/02/2018 09:04:11,Benign,2018-02-23 09:04:11,2018-02-23 09:04:116

In [67]:
ds3_labels

,Dst Port,Protocol,Timestamp,Label,date,id,p
0,22,6,22/02/2018 08:26:03,Benign,2018-02-22 08:26:03,2018-02-22 08:26:036,AM
1,34989,6,22/02/2018 08:26:24,Benign,2018-02-22 08:26:24,2018-02-22 08:26:246,AM
2,500,17,22/02/2018 08:25:10,Benign,2018-02-22 08:25:10,2018-02-22 08:25:1017,AM
3,500,17,22/02/2018 08:25:10,Benign,2018-02-22 08:25:10,2018-02-22 08:25:1017,AM
4,500,17,22/02/2018 08:24:59,Benign,2018-02-22 08:24:59,2018-02-22 08:24:5917,AM
...,...,...,...,...,...,...,...
2097145,54116,6,23/02/2018 09:00:54,Benign,2018-02-23 09:00:54,2018-02-23 09:00:546,AM
2097146,33914,6,23/02/2018 12:31:42,Benign,2018-02-23 12:31:42,2018-02-23 12:31:426,AM
2097147,53,17,23/02/2018 12:15:24,Benign,2018-02-23 12:15:24,2018-02-23 12:15:2417,AM
2097148,3389,6,23/02/2018 12:45:39,Benign,2018-02-23 12:45:39,2018-02-23 12:45:396,AM
2097149,445,6,23/02/2018 09:04:11,Benign,2018-02-23 09:04:11,2018-02-23 09:04:116,AM

In [65]:
ds2_labels['date']=pd.to_datetime(ds2_labels[' Timestamp'],format="%d/%m/%Y %H:%M")
ds3_labels['date']=pd.to_datetime(ds3_labels['Timestamp'])

In [5]:
#ds2_labels['date']

In [6]:
#print(ds3_labels[1048570:1048580])

In [7]:
#ds3_labels['p']=np.where((ds3_labels['date'].dt.hour>=1) & (ds3_labels['date'].dt.hour<=7), "PM", "AM")

In [68]:
ds2_labels['p']=np.where(ds2_labels.index<=150813, "AM","PM")
ds3_labels['p']=np.where((ds3_labels['date'].dt.hour>=1) & (ds3_labels['date'].dt.hour<=7), "PM", "AM")

In [69]:
ds2_labels['date']= ds2_labels['date'].astype(str)+" "+ds2_labels['p']
ds3_labels['date']= ds3_labels['date'].astype(str)+" "+ds3_labels['p']

In [70]:

ds2_labels['date']=pd.to_datetime(ds2_labels['date'], format="%Y-%m-%d %I:%M:%S %p")
ds3_labels['date']=pd.to_datetime(ds3_labels['date'], format="%Y-%m-%d %I:%M:%S %p")

In [14]:
snort_ds2_2017=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds2_snort/2017.csv')
snort_ds2_2018=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds2_snort/2018.csv')
snort_ds2_2019=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds2_snort/2019.csv')
snort_ds2_2020=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds2_snort/2020.csv')
suricata_ds2_2017=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds2_suricata/2017.csv')
suricata_ds2_2018=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds2_suricata/2018.csv')
suricata_ds2_2019=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds2_suricata/2019.csv')
suricata_ds2_2020=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds2_suricata/2020.csv')

In [15]:
snort_ds3_2017=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds3_snort/2017.csv')
snort_ds3_2018=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds3_snort/2018.csv')
snort_ds3_2019=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds3_snort/2019.csv')
snort_ds3_2020=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds3_snort/2020.csv')
suricata_ds3_2017=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds3_suricata/2017.csv')
suricata_ds3_2018=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds3_suricata/2018.csv')
suricata_ds3_2019=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds3_suricata/2019.csv')
suricata_ds3_2020=pd.read_csv('/home/exp-1/Desktop/data/Alerts/Alerts_csv/ds3_suricata/2020.csv')

In [16]:
suricata_ds2_2017['date']=pd.to_datetime(suricata_ds2_2017['timestamp'], utc=True)
suricata_ds2_2017['date'] = suricata_ds2_2017['date'].map(lambda x: str(x)[:-13])
suricata_ds3_2017['date']=pd.to_datetime(suricata_ds3_2017['timestamp'], utc=True)
suricata_ds3_2017['date'] = suricata_ds3_2017['date'].map(lambda x: str(x)[:-13])
suricata_ds2_2018['date']=pd.to_datetime(suricata_ds2_2018['timestamp'], utc=True)
suricata_ds2_2018['date'] = suricata_ds2_2018['date'].map(lambda x: str(x)[:-13])
suricata_ds3_2018['date']=pd.to_datetime(suricata_ds3_2018['timestamp'], utc=True)
suricata_ds3_2018['date'] = suricata_ds3_2018['date'].map(lambda x: str(x)[:-13])
suricata_ds2_2019['date']=pd.to_datetime(suricata_ds2_2019['timestamp'], utc=True)
suricata_ds2_2019['date'] = suricata_ds2_2019['date'].map(lambda x: str(x)[:-13])
suricata_ds3_2019['date']=pd.to_datetime(suricata_ds3_2019['timestamp'], utc=True)
suricata_ds3_2019['date'] = suricata_ds3_2019['date'].map(lambda x: str(x)[:-13])
suricata_ds2_2020['date']=pd.to_datetime(suricata_ds2_2020['timestamp'], utc=True)
suricata_ds2_2020['date'] = suricata_ds2_2020['date'].map(lambda x: str(x)[:-13])
suricata_ds3_2020['date']=pd.to_datetime(suricata_ds3_2020['timestamp'], utc=True)
suricata_ds3_2020['date'] = suricata_ds3_2020['date'].map(lambda x: str(x)[:-13])

In [92]:
ds2_labels

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Label,date,p,date2,id
0,192.168.10.3-192.168.10.50-389-33898-6,192.168.10.50,33898.0,192.168.10.3,389.0,6.0,6/7/2017 8:59,BENIGN,2017-07-06 08:59:00,AM,2017-07-06 11:59:00,192.168.10.50-192.168.10.3-33898-389-2017-07-06 11:59
1,192.168.10.3-192.168.10.50-389-33904-6,192.168.10.50,33904.0,192.168.10.3,389.0,6.0,6/7/2017 8:59,BENIGN,2017-07-06 08:59:00,AM,2017-07-06 11:59:00,192.168.10.50-192.168.10.3-33904-389-2017-07-06 11:59
2,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0.0,8.0.6.4,0.0,0.0,6/7/2017 8:59,BENIGN,2017-07-06 08:59:00,AM,2017-07-06 11:59:00,8.6.0.1-8.0.6.4-0-0-2017-07-06 11:59
3,192.168.10.14-65.55.44.109-59135-443-6,192.168.10.14,59135.0,65.55.44.109,443.0,6.0,6/7/2017 8:59,BENIGN,2017-07-06 08:59:00,AM,2017-07-06 11:59:00,192.168.10.14-65.55.44.109-59135-443-2017-07-06 11:59
4,192.168.10.3-192.168.10.14-53-59555-17,192.168.10.14,59555.0,192.168.10.3,53.0,17.0,6/7/2017 8:59,BENIGN,2017-07-06 08:59:00,AM,2017-07-06 11:59:00,192.168.10.14-192.168.10.3-59555-53-2017-07-06 11:59
...,...,...,...,...,...,...,...,...,...,...,...,...
458963,192.168.10.51-91.189.94.25-34353-80-6,192.168.10.51,34353.0,91.189.94.25,80.0,6.0,6/7/2017 5:04,BENIGN,2017-07-06 17:04:00,PM,2017-07-06 20:04:00,192.168.10.51-91.189.94.25-34353-80-2017-07-06 20:04
458964,192.168.10.51-91.189.94.25-34353-80-6,192.168.10.51,34353.0,91.189.94.25,80.0,6.0,6/7/2017 5:04,BENIGN,2017-07-06 17:04:00,PM,2017-07-06 20:04:00,192.168.10.51-91.189.94.25-34353-80-2017-07-06 20:04
458965,192.168.10.14-40.112.213.22-52024-80-6,192.168.10.14,52024.0,40.112.213.22,80.0,6.0,6/7/2017 5:04,BENIGN,2017-07-06 17:04:00,PM,2017-07-06 20:04:00,192.168.10.14-40.112.213.22-52024-80-2017-07-06 20:04
458966,192.168.10.255-192.168.10.50-138-138-17,192.168.10.50,138.0,192.168.10.255,138.0,17.0,6/7/2017 5:04,BENIGN,2017-07-06 17:04:00,PM,2017-07-06 20:04:00,192.168.10.50-192.168.10.255-138-138-2017-07-06 20:04
458967,192.168.10.51-91.189.94.25-34353-80-6,192.168.10.51,34353.0,91.189.94.25,80.0,6.0,6/7/2017 5:04,BENIGN,2017-07-06 17:04:00,PM,2017-07-06 20:04:00,192.168.10.51-91.189.94.25-34353-80-2017-07-06 20:04

In [97]:
suricata_ds2_2017

,timestamp,src_ip,dest_ip,src_port,dest_port,proto,event_type,alert.signature,alert.signature_id,id,date
0,2017-07-06T05:01:02.041670-0700,158.69.247.184,192.168.10.12,123.0,123.0,UDP,alert,ET TOR Known Tor Relay/Router (Not Exit) Node Traffic group 172,2522342.0,158.69.247.184-192.168.10.12-123-123-2017-07-06 12:01:02,2017-07-06 12:01:02
1,2017-07-06T05:01:38.412414-0700,13.107.4.50,192.168.10.15,80.0,49452.0,TCP,alert,ET POLICY PE EXE or DLL Windows file download,2000419.0,13.107.4.50-192.168.10.15-80-49452-2017-07-06 12:01:38,2017-07-06 12:01:38
2,2017-07-06T05:05:42.833984-0700,13.107.4.50,192.168.10.15,80.0,49474.0,TCP,alert,ET POLICY PE EXE or DLL Windows file download,2000419.0,13.107.4.50-192.168.10.15-80-49474-2017-07-06 12:05:42,2017-07-06 12:05:42
3,2017-07-06T05:09:04.787379-0700,192.168.10.5,23.50.75.27,49332.0,80.0,TCP,alert,ET POLICY Vulnerable Java Version 1.8.x Detected,2019401.0,192.168.10.5-23.50.75.27-49332-80-2017-07-06 12:09:04,2017-07-06 12:09:04
4,2017-07-06T05:09:04.924779-0700,192.168.10.5,23.50.75.27,49333.0,80.0,TCP,alert,ET POLICY Vulnerable Java Version 1.8.x Detected,2019401.0,192.168.10.5-23.50.75.27-49333-80-2017-07-06 12:09:04,2017-07-06 12:09:04
...,...,...,...,...,...,...,...,...,...,...,...
24110,2017-07-06T12:49:54.152579-0700,192.168.10.8,192.225.158.2,61101.0,3478.0,UDP,alert,ET INFO Session Traversal Utilities for NAT (STUN Binding Request),2016149.0,192.168.10.8-192.225.158.2-61101-3478-2017-07-06 19:49:54,2017-07-06 19:49:54
24111,2017-07-06T12:49:54.243142-0700,192.225.158.2,192.168.10.8,3478.0,61101.0,UDP,alert,ET INFO Session Traversal Utilities for NAT (STUN Binding Response),2016150.0,192.225.158.2-192.168.10.8-3478-61101-2017-07-06 19:49:54,2017-07-06 19:49:54
24112,2017-07-06T12:54:01.822790-0700,212.239.56.65,192.168.10.25,443.0,53873.0,TCP,alert,ET POLICY SSLv3 outbound connection from client vulnerable to POODLE attack,2019416.0,212.239.56.65-192.168.10.25-443-53873-2017-07-06 19:54:01,2017-07-06 19:54:01
24113,2017-07-06T12:56:57.291412-0700,158.69.247.184,192.168.10.19,123.0,123.0,UDP,alert,ET TOR Known Tor Relay/Router (Not Exit) Node Traffic group 172,2522342.0,158.69.247.184-192.168.10.19-123-123-2017-07-06 19:56:57,2017-07-06 19:56:57
24114,2017-07-06T12:59:58.628241-0700,212.239.56.65,192.168.10.25,443.0,53996.0,TCP,alert,ET POLICY SSLv3 outbound connection from client vulnerable to POODLE attack,2019416.0,212.239.56.65-192.168.10.25-443-53996-2017-07-06 19:59:58,2017-07-06 19:59:58

In [48]:
snort_ds2_2017['id']=snort_ds2_2017['event.source-ip']+'-'+snort_ds2_2017['event.destination-ip']+'-'+snort_ds2_2017['event.sport-itype'].astype(int).astype(str)+'-'+snort_ds2_2017['event.dport-icode'].astype(int).astype(str)+'-'+snort_ds2_2017['date'].astype(str)
snort_ds2_2018['id']=snort_ds2_2018['event.source-ip']+'-'+snort_ds2_2018['event.destination-ip']+'-'+snort_ds2_2018['event.sport-itype'].astype(int).astype(str)+'-'+snort_ds2_2018['event.dport-icode'].astype(int).astype(str)+'-'+snort_ds2_2018['date'].astype(str)
snort_ds2_2019['id']=snort_ds2_2019['event.source-ip']+'-'+snort_ds2_2019['event.destination-ip']+'-'+snort_ds2_2019['event.sport-itype'].astype(int).astype(str)+'-'+snort_ds2_2019['event.dport-icode'].astype(int).astype(str)+'-'+snort_ds2_2019['date'].astype(str)
snort_ds2_2020['id']=snort_ds2_2020['event.source-ip']+'-'+snort_ds2_2020['event.destination-ip']+'-'+snort_ds2_2020['event.sport-itype'].astype(int).astype(str)+'-'+snort_ds2_2020['event.dport-icode'].astype(int).astype(str)+'-'+snort_ds2_2020['date'].astype(str)
suricata_ds2_2017['id']=suricata_ds2_2017['src_ip']+'-'+suricata_ds2_2017['dest_ip']+'-'+suricata_ds2_2017['src_port'].astype(int).astype(str)+'-'+suricata_ds2_2017['dest_port'].astype(int).astype(str)+'-'+suricata_ds2_2017['date'].astype(str)
suricata_ds2_2018['id']=suricata_ds2_2018['src_ip']+'-'+suricata_ds2_2018['dest_ip']+'-'+suricata_ds2_2018['src_port'].astype(int).astype(str)+'-'+suricata_ds2_2018['dest_port'].astype(int).astype(str)+'-'+suricata_ds2_2018['date'].astype(str)
suricata_ds2_2019['id']=suricata_ds2_2019['src_ip']+'-'+suricata_ds2_2019['dest_ip']+'-'+suricata_ds2_2019['src_port'].astype(int).astype(str)+'-'+suricata_ds2_2019['dest_port'].astype(int).astype(str)+'-'+suricata_ds2_2019['date'].astype(str)
suricata_ds2_2020['id']=suricata_ds2_2020['src_ip']+'-'+suricata_ds2_2020['dest_ip']+'-'+suricata_ds2_2020['src_port'].astype(int).astype(str)+'-'+suricata_ds2_2020['dest_port'].astype(int).astype(str)+'-'+suricata_ds2_2020['date'].astype(str)

In [76]:
from datetime import datetime, timedelta
ds2_labels['date2']=ds2_labels['date']+timedelta(hours=3)

In [82]:
ds2_labels['id']=ds2_labels[' Source IP']+'-'+ds2_labels[' Destination IP']+'-'+ds2_labels[' Source Port'].astype(int).astype(str)+'-'+ds2_labels[' Destination Port'].astype(int).astype(str)+'-'+ds2_labels['date2'].astype(str)

In [90]:
ds2_labels['id']=ds2_labels['id'].map(lambda x: str(x)[:-3])

In [98]:
#snort_ds2_2017['id']=snort_ds2_2017['id'].map(lambda x: str(x)[:-3])
#snort_ds2_2018['id']=snort_ds2_2018['id'].map(lambda x: str(x)[:-3])
#snort_ds2_2019['id']=snort_ds2_2019['id'].map(lambda x: str(x)[:-3])
#snort_ds2_2020['id']=snort_ds2_2020['id'].map(lambda x: str(x)[:-3])
suricata_ds2_2017['id']=suricata_ds2_2017['id'].map(lambda x: str(x)[:-3])
suricata_ds2_2018['id']=suricata_ds2_2018['id'].map(lambda x: str(x)[:-3])
suricata_ds2_2019['id']=suricata_ds2_2019['id'].map(lambda x: str(x)[:-3])
suricata_ds2_2020['id']=suricata_ds2_2020['id'].map(lambda x: str(x)[:-3])

In [129]:
suricata_ds2_2017['id'].isin(ds2_labels['id']).value_counts()

True     13189
False    10926
Name: id, dtype: int64

In [116]:
ds2_labels['id'].value_counts()

192.168.10.17-61.184.116.79-47724-443-2017-07-06 15:03    17
192.168.10.17-61.184.116.79-47719-443-2017-07-06 15:02    12
61.184.116.79-192.168.10.17-443-47724-2017-07-06 15:03     9
192.168.10.8-192.168.10.14-34053-135-2017-07-06 18:19      8
192.168.10.8-192.168.10.14-45338-135-2017-07-06 18:28      8
                                                          ..
192.168.10.12-192.168.10.3-43705-53-2017-07-06 15:14       1
192.168.10.12-192.168.10.3-41093-53-2017-07-06 15:14       1
192.168.10.12-192.168.10.3-21242-53-2017-07-06 15:14       1
192.168.10.12-192.168.10.3-27233-53-2017-07-06 15:14       1
192.168.10.50-192.168.10.255-138-138-2017-07-06 20:04      1
Name: id, Length: 427225, dtype: int64

In [117]:
snort_ds2_2017['id'].value_counts()

192.168.10.9-54.192.48.130-7642-443-2017-07-06 17:47      172
192.168.10.12-23.15.4.18-60194-80-2017-07-06 16:54        133
192.168.10.16-172.217.10.14-39508-443-2017-07-06 16:12     95
192.168.10.17-61.184.116.79-47724-443-2017-07-06 15:03     59
192.168.10.16-104.20.11.37-45134-80-2017-07-06 18:15       42
                                                         ...
157.240.18.19-192.168.10.9-443-3508-2017-07-06 14:49        1
157.240.2.35-192.168.10.16-443-50620-2017-07-06 14:49       1
192.168.10.51-192.168.10.50-46275-22-2017-07-06 14:49       1
192.168.10.50-192.168.10.51-22-46274-2017-07-06 14:48       1
74.119.118.74-192.168.10.51-80-44693-2017-07-06 19:42       1
Name: id, Length: 23287, dtype: int64

In [118]:
snort_ds2_2017['POSITIVES'] = ((snort_ds2_2017['id'].isin(ds2_labels['id'])) & (ds2_labels[' Label']!='BENIGN'))
snort_ds2_2018['POSITIVES'] = ((snort_ds2_2018['id'].isin(ds2_labels['id'])) & (ds2_labels[' Label']!='BENIGN'))
snort_ds2_2019['POSITIVES'] = ((snort_ds2_2019['id'].isin(ds2_labels['id'])) & (ds2_labels[' Label']!='BENIGN'))
snort_ds2_2020['POSITIVES'] = ((snort_ds2_2020['id'].isin(ds2_labels['id'])) & (ds2_labels[' Label']!='BENIGN'))

In [130]:
suricata_ds2_2017['POSITIVES'] = ((suricata_ds2_2017['id'].isin(ds2_labels['id'])) & (ds2_labels[' Label']!='BENIGN'))

In [131]:
suricata_ds2_2017['POSITIVES'].value_counts()

False    24010
True       105
Name: POSITIVES, dtype: int64

In [128]:
ds2_labels[' Label'].value_counts()

BENIGN                        456752
Web Attack â€“ Brute Force        1507
Web Attack â€“ XSS                 652
Infiltration                      36
Web Attack â€“ Sql Injection        21
Name:  Label, dtype: int64

In [127]:
ds3_labels['Label'].value_counts()

Benign              2096222
Brute Force -Web        611
Brute Force -XSS        230
SQL Injection            87
Name: Label, dtype: int64

In [135]:
suricata_ds2_2020

,timestamp,src_ip,dest_ip,src_port,dest_port,proto,event_type,alert.signature,alert.signature_id,id,date
0,2017-07-06T05:03:59.960131-0700,192.168.10.5,23.194.182.93,49223.0,80.0,TCP,alert,ET USER_AGENTS Microsoft Device Metadata Retrieval Client User-Agent,2027390.0,192.168.10.5-23.194.182.93-49223-80-2017-07-06 12:03,2017-07-06 12:03:59
1,2017-07-06T05:03:59.565258-0700,192.168.10.5,23.194.182.93,49217.0,80.0,TCP,alert,ET USER_AGENTS Microsoft Device Metadata Retrieval Client User-Agent,2027390.0,192.168.10.5-23.194.182.93-49217-80-2017-07-06 12:03,2017-07-06 12:03:59
2,2017-07-06T05:04:01.140526-0700,192.168.10.5,23.194.182.93,49226.0,80.0,TCP,alert,ET USER_AGENTS Microsoft Device Metadata Retrieval Client User-Agent,2027390.0,192.168.10.5-23.194.182.93-49226-80-2017-07-06 12:04,2017-07-06 12:04:01
3,2017-07-06T05:03:59.899554-0700,192.168.10.5,40.112.210.171,49218.0,80.0,TCP,alert,ET INFO Windows OS Submitting USB Metadata to Microsoft,2025275.0,192.168.10.5-40.112.210.171-49218-80-2017-07-06 12:03,2017-07-06 12:03:59
4,2017-07-06T05:03:59.899554-0700,192.168.10.5,40.112.210.171,49218.0,80.0,TCP,alert,ET USER_AGENTS Microsoft Device Metadata Retrieval Client User-Agent,2027390.0,192.168.10.5-40.112.210.171-49218-80-2017-07-06 12:03,2017-07-06 12:03:59
...,...,...,...,...,...,...,...,...,...,...,...
24806,2017-07-06T13:01:44.395004-0700,192.168.10.5,104.97.126.55,58692.0,80.0,TCP,alert,ET USER_AGENTS Microsoft Device Metadata Retrieval Client User-Agent,2027390.0,192.168.10.5-104.97.126.55-58692-80-2017-07-06 20:01,2017-07-06 20:01:44
24807,2017-07-06T13:02:17.508684-0700,192.168.10.14,23.210.86.11,52023.0,80.0,TCP,alert,ET USER_AGENTS Microsoft Device Metadata Retrieval Client User-Agent,2027390.0,192.168.10.14-23.210.86.11-52023-80-2017-07-06 20:02,2017-07-06 20:02:17
24808,2017-07-06T13:02:17.748621-0700,192.168.10.14,23.210.86.11,52025.0,80.0,TCP,alert,ET USER_AGENTS Microsoft Device Metadata Retrieval Client User-Agent,2027390.0,192.168.10.14-23.210.86.11-52025-80-2017-07-06 20:02,2017-07-06 20:02:17
24809,2017-07-06T13:02:36.265587-0700,192.168.10.14,23.210.86.11,52207.0,80.0,TCP,alert,ET USER_AGENTS Microsoft Device Metadata Retrieval Client User-Agent,2027390.0,192.168.10.14-23.210.86.11-52207-80-2017-07-06 20:02,2017-07-06 20:02:36
24810,2017-07-06T13:02:36.417354-0700,192.168.10.14,23.210.86.11,52208.0,80.0,TCP,alert,ET USER_AGENTS Microsoft Device Metadata Retrieval Client User-Agent,2027390.0,192.168.10.14-23.210.86.11-52208-80-2017-07-06 20:02,2017-07-06 20:02:36

In [15]:
df_count_negative = df_labels['Label'].value_counts()

In [16]:
print(df_count_negative)

TFTP      186054
BENIGN     13944
Name: Label, dtype: int64

In [18]:
df_count_negative['true']=df_count_negative['BENIGN']
df_count_negative['false']=df_count_negative['TFTP']

In [19]:
print(df_count_negative)

TFTP      186054
BENIGN     13944
true       13944
false     186054
Name: Label, dtype: int64

In [20]:
col_list = ['true', 'false']
df_count_negative = df_count_negative[col_list]

In [21]:
print(df_count_negative)

true      13944
false    186054
Name: Label, dtype: int64

In [33]:
with open (r"/home/exp-1/Desktop/data/count_positive.csv", mode = 'a') as f:
    df_count_positive.to_csv(f, header=f.tell()==0, index = True)

In [22]:
with open (r"/home/exp-1/Desktop/data/count_negative.csv", mode = 'a') as f:
    df_count_negative.to_csv(f, header=f.tell()==0, index = True)